'use strict'
// auto-generated by boundation, do not update manually
/** @type {typeof import("./compiled-types/test.d.ts") } */
module.exports = require('editions').requirePackage(
	__dirname,
	require,
	'test.js'
)
